services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
  frontend:
    image: node:20-alpine
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    depends_on:
      - api
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
